name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: reinaldoper
          template: classic
          base: header, activity, community, repositories
          config_timezone: America/Sao_Paulo

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 6

          plugin_stars: yes
          plugin_stars_limit: 4

          plugin_repositories: yes
          plugin_repositories_featured: reinaldoper/mario-kart-js, reinaldoper/portfolio

          plugin_traffic: yes
          plugin_lines: yes
